### ISSUE TITLE
Fixing the Keybind menu display & ReSeeding anticheat flag issue

### ISSUE THREAD

**Issue by Scarlaid** [Taskeren/mineQuery-1.17#7]
![image](https://user-images.githubusercontent.com/90851437/205449416-418f724b-5e82-4e44-bc05-50191a6b2c4c.png)

Maybe? It looks so unnecessary long

**Comment by Scarlaid** [comment]
Oh yea I also wanna inform stuff about the ReSeeding feature

So this mod use left click to replant the crops, sadly to say, it tickles the Anticheat alot in some servers
My suggestion for this is using right-click with the same function

If video needed I will provide

**Comment by Taskeren** [comment]
Actually the mod is not replant the crops by left-clicking.
Technically, it sends a right-click(interact) packet(in fabric, it called PlayerInteractBlockC2SPacket) to servers after a successful harvest with a 5ms delay.
And I have no idea how Anticheats detect it, so use at your own risk. (btw, I've also been deprecated because of it. lol)

**Comment by Scarlaid** [comment]
I have checked the flags again and it's about `Post BlockPlace packets`
![image](https://user-images.githubusercontent.com/90851437/205469844-cd6be206-3b48-4c32-af56-3393f085fa3e.png)

Might be the delay is too short? 
Oh yeah, this was Vulcan Anticheat I'm using and dealing
